### ISSUE TITLE
What should I do if I don't need to play the interface and just have a sound

### ISSUE THREAD

**Issue by lfh22** [nklhtv/react-native-vlc2#12]
What should I do if I don't need to play the interface and just have a sound

**Comment by nklhtv** [comment]
if you want to play just the sound you could set the width and height of the component to 0

**Comment by lfh22** [comment]
@NikolaBorislavovHristov   I  set the width and height of the component to 0, can't play

**Comment by nklhtv** [comment]
@lfh22 The example in the master branch plays the audio when the style value is replaced with 
`style={{width: 0, height: 0}}`
