### ISSUE TITLE
No suitable constructor found for VLCVideoPackage(no arguments)

### ISSUE THREAD

**Issue by StevenB45** [nklhtv/react-native-vlc2#14]
Hello,

I can't use this plugin, can you help me? I can't build the application: 

`/MainApplication.java:27: error: no suitable constructor found for VLCVideoPackage(no arguments)
          new VLCVideoPackage()
          ^
    constructor VLCVideoPackage.VLCVideoPackage(Application) is not applicable
      (actual and formal argument lists differ in length)
    constructor VLCVideoPackage.VLCVideoPackage(Application,ArrayList<String>) is not applicable
      (actual and formal argument lists differ in length)
    constructor VLCVideoPackage.VLCVideoPackage(Application,OnKeyListener) is not applicable
      (actual and formal argument lists differ in length)
    constructor VLCVideoPackage.VLCVideoPackage(Application,VLCVideoCallbackManager) is not applicable
      (actual and formal argument lists differ in length)
    constructor VLCVideoPackage.VLCVideoPackage(Application,ArrayList<String>,OnKeyListener) is not applicable
      (actual and formal argument lists differ in length)
    constructor VLCVideoPackage.VLCVideoPackage(Application,ArrayList<String>,VLCVideoCallbackManager) is not applicable
      (actual and formal argument lists differ in length)
    constructor VLCVideoPackage.VLCVideoPackage(Application,OnKeyListener,VLCVideoCallbackManager) is not applicable
      (actual and formal argument lists differ in length)
    constructor VLCVideoPackage.VLCVideoPackage(Application,ArrayList<String>,OnKeyListener,VLCVideoCallbackManager) is not applicable
      (actual and formal argument lists differ in length)
1 error
`
RN 0.59.10.

Thank you.

**Comment by nklhtv** [comment]
In the `getPackages` method in the application class you could use `new VLCVideoPackage(this)`.
This is the very basic usage. To constuct libVLC object you must provide context.
here is the example: https://github.com/NikolaBorislavovHristov/react-native-vlc2/blob/master/example/android/app/src/main/java/com/example/MainApplication.java#L28
and here are all the constructors you could use: https://github.com/NikolaBorislavovHristov/react-native-vlc2/blob/master/android/src/main/java/com/stellarscript/vlcvideo/VLCVideoPackage.java

**Comment by StevenB45** [comment]
OK, thank you so much!
