### ISSUE TITLE
rtsp: slow closing after play

### ISSUE THREAD

**Issue by temaivanoff** [nklhtv/react-native-vlc2#8]
I tried to call pause () with componentWillUnmount but also slowly.
How to stop the vlc so that there is no delay when the component is destroyed?

**Comment by nklhtv** [comment]
Can you give me video url to help me reproduce this issue?

**Comment by temaivanoff** [comment]
rtsp://root:1234@176.193.75.143:7888/videoMain

**Comment by temaivanoff** [comment]
may be create stop method which will force clear vlcIt may be necessary to make a stop method which will force the components?

**Comment by nklhtv** [comment]
The bottleneck is somewhere else. I will debug it tomorrow or by the end of the week.

**Comment by temaivanoff** [comment]
I conducted the investigation and found out that this problem is libvlc with rtsp work and fixed in version 2.1.0

**Comment by nklhtv** [comment]
This plugin still use libvlc 2.0.6
The latest version must be compiled

**Comment by temaivanoff** [comment]
Hi, there are a lot of changes in the latest versions.
I used `de.mrmaffen:libvlc-android:2.1.12`
In this version there is no `Callback -> public void onNewLayout`  replace `OnNewVideoLayoutListener  -> public  void onNewVideoLayout` also no `Callback -> public void onHardwareAccelerationError`  expelled
everything works a bug in this version is fixed, but since the onNewLayout method is not called and the display is not correctly displayed
I can not understand where I should now make the image adjustment in version 2.1.12
`OnNewVideoLayoutListener` is triggered when the screen changed and not at startup
do you have any ideas?
![screen](https://user-images.githubusercontent.com/11176223/35724928-812cf140-0810-11e8-87bc-d2ff8cc3f0f9.png)

lib 2.1.12: https://github.com/mrmaffen/vlc-android-sdk/blob/master/libvlc-android/src/main/java/org/videolan/libvlc/IVLCVout.java

**Comment by temaivanoff** [comment]
Fixes #9

**Comment by nklhtv** [comment]
try [v2.5.17-rc1](https://github.com/NikolaBorislavovHristov/react-native-vlc2/releases/tag/v2.5.17-rc1)

**Comment by NikolaBorislavovHristov** [comment]
it is still in proggress

**Comment by temaivanoff** [comment]
it's work! 👍

**Comment by nklhtv** [comment]
soon it will be released in npm
